<?php

namespace LpdwBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getById($id)
    {
        try {
            $post = $this
                ->createQueryBuilder('p')
                ->where('p.id = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getSingleResult()
                // ->getOneOrNullResult() équivalent au getSingleResult()
            ;

            return $post;
        } catch (\Exception $ex) {
            return null;
        }
    }
}
