<?php

namespace LpdwBundle\Repository;

/**
 * PostLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
