lpdw_homepage:
    path:     /
    defaults: { _controller: LpdwBundle:Default:index }

lpdw_posts:
    path:     /posts
    defaults: { _controller: LpdwBundle:Post:posts }

lpdw_post:
    path:     /posts/{id}
    defaults: { _controller: LpdwBundle:Post:post }
    requirements:
        id: \d+

lpdw_new_post:
    path:     /posts/new
    defaults: { _controller: LpdwBundle:Post:new }

lpdw_login:
    path: /login
    defaults: { _controller: LpdwBundle:Login:login }

lpdw_login_check:
    path: /login_check
    defaults: { _controller: LpdwBundle:Login:loginCheck }

lpdw_logout:
    path: /logout
